version: "3.7"

services:
  final-exam:
    image: node:16.8.0
    command: sh -c "npm install && npm run dev"
    ports:
       - 3000:3000
    working_dir: /final-exam
    volumes:
      - ./:/final-exam

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DB: ${DB_NAME}
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - a:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    stdin_open: true
    tty: true
volumes:
  a: